version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: papi
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: lufragoso/ac2
    environment:
      SPRING_PROFILES_ACTIVE: staging
      DB_HOST: database
    ports:
      - "8787:8787"
    depends_on:
      - database
volumes:
  db-volume: